version: '3.9'
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik
    volumes:
      - /mnt/moosefs/apps/Sonarr:/config
      - /mnt/moosefs/series/shows:/tv
      - /mnt/moosefs/series/shows:/series
      - /mnt/moosefs/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    deploy:
      replicas: 1
      labels:
        - traefik.constraint-label=traefik
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.sonarr.entrypoints=web
        - traefik.http.routers.sonarr.rule=Host(`sonarr.cofhome`)
        - traefik.http.routers.sonarr.service=sonarr
        - traefik.http.services.sonarr.loadbalancer.server.port=8989
        - traefik.port=80

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik:
    external: true
