version: '3.9'

services:
   traefik:
    image: traefik:v2.11.6
    ports:
    # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
     - 80:80
     - 8080:8080
    deploy:
       replicas: 3
       placement:
         max_replicas_per_node: 1
          
       labels:
        # Enable Traefik for this service, to make it available in the public network
          - traefik.enable=true
          - traefik.docker.network=traefik
          - traefik.constraint-label=traefik
          - traefik.http.routers.traefik.dashboard=true
          - traefik.port=80
          - traefik.http.routers.traefik.rule=Host(`traefik.cofhome`)
          - traefik.http.routers.traefik.service=api@internal
          - traefik.http.services.traefik.loadbalancer.server.port=8080
          - traefik.http.routers.api.insecure=true
          - traefik.http.routers.traefik.entrypoints=web
        
           
    volumes:
       # Add Docker as a mounted volume, so that Traefik can read the labels of other services
       - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
       - --log.level=DEBUG
       - --api.insecure=true
       #- --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik`)
       - --accesslog
       - --log
       - --entrypoints.web.address=:80
       - --providers.docker
       - --providers.docker.exposedbydefault=false
       - --providers.docker.swarmmode
       #- --providers.docker.network=traefik
       - --api
       - --api.dashboard=true
    networks:
     # Use the public network created to be shared between Traefik and
     # any other service that needs to be publicly available with HTTPS
       - traefik
    restart: "unless-stopped"
networks:
   # Use the previously created public network "traefik-public", shared with other
   # services that need to be publicly available via this Traefik
   traefik:
      external: true
