version: '3.9'
services:
  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    environment:
      - AUTO_UPDATE=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik
    volumes:
      - /mnt/moosefs/apps/Jackett:/config
      - /mnt/moosefs/downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
    deploy:
      replicas: 3
      labels:
        - traefik.constraint-label=traefik
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.jackett.entrypoints=web
        - traefik.http.routers.jackett.rule=Host(`jackett.cofhome`)
        - traefik.http.routers.jackett.service=jackett
        - traefik.http.services.jackett.loadbalancer.server.port=9117
        - traefik.port=80
      placement:
        max_replicas_per_node: 1
        constraints:
          -  node.role == manager
          
networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik:
    external: true
