version: '3.9'
services:
  agent:
    image: portainer/agent:latest
    ports: 
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always 
    deploy:
      replicas: 2
